server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: otel-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: otel-app-logs
      service_name: sale-service
      __path__: /logs/otel-logs.json
  pipeline_stages:
  - json:
      expressions:
        timestamp: timestamp
        level: level
        message: msg
        source: source
        service: service
  - timestamp:
      source: timestamp
      format: RFC3339
  - labels:
      level:
      service:

- job_name: otel-collector-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: otel-collector-logs
      service_name: otel-collector
      __path__: /logs/otel-collector-logs.json