// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SaleRecipe struct {
	ID          int32
	Ingredients []int32
}

type SaleUnit struct {
	ID           int32
	Name         string
	PosID        int32
	Price        string
	SaleRecipeID int32
	CreatedAt    pgtype.Date
}
