// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SaleRecipe struct {
	ID          int64
	Ingredients []int32
}

type SaleUnit struct {
	ID           int64
	Name         string
	PosID        int32
	Price        int32
	SaleRecipeID int32
	CreatedAt    pgtype.Timestamptz
}
