// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sale struct {
	ID        int64
	PosID     int32
	Price     int32
	RecipeID  int32
	OrderID   int32
	CreatedAt pgtype.Timestamptz
}
