// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sale.unit.sql

package models

import (
	"context"
)

const createSaleUnit = `-- name: CreateSaleUnit :one
INSERT INTO sale_unit (
    name, pos_id, price, sale_recipe_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, pos_id, price, sale_recipe_id, "createdAt"
`

type CreateSaleUnitParams struct {
	Name         string
	PosID        int32
	Price        string
	SaleRecipeID int32
}

func (q *Queries) CreateSaleUnit(ctx context.Context, arg CreateSaleUnitParams) (SaleUnit, error) {
	row := q.db.QueryRow(ctx, createSaleUnit,
		arg.Name,
		arg.PosID,
		arg.Price,
		arg.SaleRecipeID,
	)
	var i SaleUnit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosID,
		&i.Price,
		&i.SaleRecipeID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSaleUnit = `-- name: DeleteSaleUnit :exec
DELETE FROM sale_unit
WHERE id = $1
`

func (q *Queries) DeleteSaleUnit(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSaleUnit, id)
	return err
}

const getSaleUnit = `-- name: GetSaleUnit :one
SELECT id, name, pos_id, price, sale_recipe_id, "createdAt" FROM sale_unit
WHERE id = $1
`

func (q *Queries) GetSaleUnit(ctx context.Context, id int32) (SaleUnit, error) {
	row := q.db.QueryRow(ctx, getSaleUnit, id)
	var i SaleUnit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosID,
		&i.Price,
		&i.SaleRecipeID,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleUnit = `-- name: ListSaleUnit :many
SELECT id, name, pos_id, price, sale_recipe_id
FROM sale_unit
LIMIT $1 OFFSET $2
`

type ListSaleUnitParams struct {
	Limit  int32
	Offset int32
}

type ListSaleUnitRow struct {
	ID           int32
	Name         string
	PosID        int32
	Price        string
	SaleRecipeID int32
}

func (q *Queries) ListSaleUnit(ctx context.Context, arg ListSaleUnitParams) ([]ListSaleUnitRow, error) {
	rows, err := q.db.Query(ctx, listSaleUnit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleUnitRow
	for rows.Next() {
		var i ListSaleUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosID,
			&i.Price,
			&i.SaleRecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleUnit = `-- name: UpdateSaleUnit :one
UPDATE sale_unit
SET name = $2,
    pos_id = $3,
    price = $4,
    sale_recipe_id = $5
WHERE id = $1
RETURNING id, name, pos_id, price, sale_recipe_id, "createdAt"
`

type UpdateSaleUnitParams struct {
	ID           int32
	Name         string
	PosID        int32
	Price        string
	SaleRecipeID int32
}

func (q *Queries) UpdateSaleUnit(ctx context.Context, arg UpdateSaleUnitParams) (SaleUnit, error) {
	row := q.db.QueryRow(ctx, updateSaleUnit,
		arg.ID,
		arg.Name,
		arg.PosID,
		arg.Price,
		arg.SaleRecipeID,
	)
	var i SaleUnit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosID,
		&i.Price,
		&i.SaleRecipeID,
		&i.CreatedAt,
	)
	return i, err
}
