// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sale.unit.sql

package models

import (
	"context"
)

const createSaleUnit = `-- name: CreateSaleUnit :one
INSERT INTO sale (
    pos_id, price, recipe_id, order_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, pos_id, price, recipe_id, order_id, created_at
`

type CreateSaleUnitParams struct {
	PosID    int32
	Price    int32
	RecipeID int32
	OrderID  int32
}

func (q *Queries) CreateSaleUnit(ctx context.Context, arg CreateSaleUnitParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSaleUnit,
		arg.PosID,
		arg.Price,
		arg.RecipeID,
		arg.OrderID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSaleUnit = `-- name: DeleteSaleUnit :exec
DELETE FROM sale
WHERE id = $1
`

func (q *Queries) DeleteSaleUnit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSaleUnit, id)
	return err
}

const getSaleUnit = `-- name: GetSaleUnit :one
SELECT id, pos_id, price, recipe_id, order_id, created_at FROM sale
WHERE id = $1
`

func (q *Queries) GetSaleUnit(ctx context.Context, id int64) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleUnit, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleUnit = `-- name: ListSaleUnit :many
SELECT id, pos_id, order_id, price, recipe_id
FROM sale
LIMIT $1 OFFSET $2
`

type ListSaleUnitParams struct {
	Limit  int32
	Offset int32
}

type ListSaleUnitRow struct {
	ID       int64
	PosID    int32
	OrderID  int32
	Price    int32
	RecipeID int32
}

func (q *Queries) ListSaleUnit(ctx context.Context, arg ListSaleUnitParams) ([]ListSaleUnitRow, error) {
	rows, err := q.db.Query(ctx, listSaleUnit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleUnitRow
	for rows.Next() {
		var i ListSaleUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.PosID,
			&i.OrderID,
			&i.Price,
			&i.RecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleUnit = `-- name: UpdateSaleUnit :one
UPDATE sale
SET 
    pos_id = $2,
    price = $3,
    recipe_id = $4,
    order_id = $5
WHERE id = $1
RETURNING id, pos_id, price, recipe_id, order_id, created_at
`

type UpdateSaleUnitParams struct {
	ID       int64
	PosID    int32
	Price    int32
	RecipeID int32
	OrderID  int32
}

func (q *Queries) UpdateSaleUnit(ctx context.Context, arg UpdateSaleUnitParams) (Sale, error) {
	row := q.db.QueryRow(ctx, updateSaleUnit,
		arg.ID,
		arg.PosID,
		arg.Price,
		arg.RecipeID,
		arg.OrderID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}
